### ISSUE TITLE
Bitstamp no fee promotion period

### ISSUE THREAD

**Issue by btcdrak** [bitcoinaverage/bitcoinaverage#159]
Bitstamp is running fee-free promotion until 17th January

https://www.bitstamp.net/article/bitstamp-is-open-for-business-better-than-ever/

```
COMMISSION-FREE TRADING 

* As a note of thanks to our loyal customers, all transactions conducted on Bitstamp through the end of the North American Bitcoin Conference -- January 17th (at 11:59pm UTC) -- will be commission-free. 
```

**Comment by bitnumus** [comment]
Hi,

Yes they are currently not integrated but I will change the message and
move them to ignored tomorrow

**Comment by btcdrak** [comment]
The Bitstamp free promotion is now over.
