### ISSUE TITLE
Coinbase new API

### ISSUE THREAD

**Issue by btcdrak** [bitcoinaverage/bitcoinaverage#161]
Please can you add the new Coinbase Exchange to bitcoinaverage?

https://docs.exchange.coinbase.com/#market-data

**Comment by bitnumus** [comment]
Hi,

They have no fees running for two months, we were made aware of the API a few days ago by charlie lee and made the decision to wait. Also they have 3 endpoints needed to get the simple set of data that we require, so have put forward this suggestion to them

**Comment by jjmardlin** [comment]
Just curious, why are no-fee exchanges being excluded? I've wondered for a while, but never bothered to ask.

**Comment by bitnumus** [comment]
We provide a weighted average, trading without fees enables bots to
essentially trade with themselves and this causes inflated volume (many
have said fake volume but that's a little strong, inflated is a better
word). This is why all Chinese exchanges have huge volume and this would
hugely distort our average, in many people's opinion, wrongly.

This is something we've discussed with the exchange owners and also
something that has been debated for a long time amongst the community. At
the end of the day we are unable to please everyone and can only go with
the majority.

Hope that explained it!

**Comment by jjmardlin** [comment]
Absolutely, and I have to agree. Watching the bots work on the coinbase exchange can be mind boggling, and it's hard to keep up. 

I think it would be worth adding that detail to the Index Formula page, and perhaps liking to it from an asterisk place beside the text "Reason: 0% fee model" where it appears.

**Comment by bitnumus** [comment]
Appreciate the feedback, I will add that to our tracker.

**Comment by bitnumus** [comment]
done a while ago!
