### ISSUE TITLE
Ajax (CORS) fail with HTTP 0 in Android Browser and Safari on iOS 

### ISSUE THREAD

**Issue by ognus** [bitcoinaverage/bitcoinaverage#164]
Hi,

I have noticed that ajax API calls to https://api.bitcoinaverage.com/ticker/global/USD fail on Android default browser and Safari on iPad. By fail I mean that api.bitcoinaverage.com responds with HTTP 0 and no body. As far as I have tested it works well on major desktop browsers (IE, Chrome, FF). 

Below is simple plunker to illustrate it (it uses jQuery, but have the same problem using AngularJS $http service):
http://plnkr.co/edit/YeFmsgCAlI7ojOrQdKDl?p=preview

I think there are 2 problems, first is that you are not setting Access-Control-Allow-Origin: * on error responses, i.e. HTTP status codes > 299 so the CORS can't kick in and we'll always get HTTP 0, which makes debugging ajax request really hard. Try https://api.bitcoinaverage.com/ticker/global/wrongURL and it will return nice HTTP 404, but doing ajax request to this url will respond with HTTP 0.

Second and the main problem I guess is that you are missing a Access-Control-Allow-Header: Origin header in the response.

Otherwise I find you ticker API really useful, thank you :)

Cheers,
Tomek

**Comment by bitnumus** [comment]
Hi Tomek,

Thanks for the issue report and detail, i'll look into this for you.

**Comment by bitnumus** [comment]
v2 is under development so this repository will no longer be maintained
