### ISSUE TITLE
Dates missing in historical CSVs

### ISSUE THREAD

**Issue by BashCo** [bitcoinaverage/bitcoinaverage#167]
per_day_all_time_history.csv skips from July to September.

2015-07-20 00:00:00,280.14,273.85,277.23,54220.36
2015-09-03 00:00:00,230.74,230.74,230.74,65168.97

It looks like new data is being added again. Is there any chance of including the missing data? 

Edit: I see now that the data is also missing from the charts as well. Bummer.

**Comment by bitnumus** [comment]
It will be added of course, we are still awaiting a snapshot of our server
from the old providers. Quite unbelievable I know!

**Comment by BashCo** [comment]
The missing data has been restored! Thanks. $5 @changetip

**Comment by bitnumus** [comment]
Sorry for how long this took, please note it's only for USD currently, I'll
work through the other asap.
