### ISSUE TITLE
Chart slider url non functional

### ISSUE THREAD

**Issue by raedah** [bitcoinaverage/bitcoinaverage#169]
Using the slider on the chart produces this url.

https://bitcoinaverage.com/charts#USD-averages-false

One problem is that it currently creates a url which says that the USD average are false, but the url just ends up returning a 1 day chart anyways regardless of the slider view it was taken from.

Proposed solution: include the 'from' and 'to' date in the URL when the slider is used. If 'from' and 'to' date are specified in the url, load the chart based on those.

extra: axis type should also be included in the url

**Comment by bitnumus** [comment]
Hi raedah,

We aren't actively developing the current production code, we have a new codebase and frontend coming soon.

If you are interested in beta access in the near future please contact us at info@bitcoinaverage.com, we could do with some testers :)
