### ISSUE TITLE
Has APIv2 permanently destroyed 

### ISSUE THREAD

**Issue by TheButterZone** [bitcoinaverage/bitcoinaverage#171]
https://github.com/fordhurley/btc-priceimg/issues/11 with non-free plans?

**Comment by shaun-ba** [comment]
The data you need here is freely available, I replied to your issue on that repository and that should be all that's needed. 

The code there hasn't been updated for 2-3years so you may want to fork, apply my change, test and then run your own fork until the maintainer accepts your pull request
