### ISSUE TITLE
I am getting bitcoinaverage/bitcoinaverage/common.js:33, throw response.statusMessage; ERROR sometimes and it crashsesh my node app

### ISSUE THREAD

**Issue by nmajethiya** [bitcoinaverage/bitcoinaverage#172]
I am calling bitcoinaverage API for ETHINR, BTCINR and XRPINR. I am sometime getting this error.

For now I am calling 3 different API as no API is available to get all 3 at the sametime. or might be I am not aware

**Comment by shaun-ba** [comment]
Hi,

The API here is not maintained, can you please raise a ticket with our
support desk and we will be happy to help!

Just email support@bitcoinaverage.com

Thanks

**Comment by nmajethiya** [comment]
Sure Thanks for reply
